name: Benchmark

on:
  push:
    branches: [ canary ]
  pull_request:
    branches: [ canary ]

jobs:
  benchmark:
    name: Run JavaScript benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Run benchmark
        run: |
          npm install
          npx babel-node --extensions ".ts" benchmark.ts | tee benchmark.txt

      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: 'benchmarkjs'
          output-file-path: benchmark.txt
          gh-pages-branch: benchmarks
          benchmark-data-dir-path: './'
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: '125%'
          fail-on-alert: true
          fail-threshold: '200%'
